#!/bin/bash
#
#   paleta para gimp e inkscape con un teclado numerico
#
while [ 1 ]; do
[ "$1" == "" ] && ID=$(xinput list | grep 13ba | cut -d= -f2 | sed 's/\t.*$//g') || ID="$1"
xinput float $ID
xinput test $ID | while read A; do
    K=$(echo $A | grep release | cut -d" " -f3)
    K1=$(echo $A | grep press | cut -d" " -f3)
    P=$(xdotool getwindowfocus getwindowname)
    echo $A
    echo "R:$K P:$K1 M:$KK"
    if [ ! "$(echo $P | grep -i gimp)" == "" ]; then
        [ "$K" == "63" ]    && xdotool key "ctrl+d"
        [ "$K" == "79" ]    && xdotool key n
        [ "$K" == "80" ]    && xdotool key k
        [ "$K" == "81" ]    && xdotool key "i"
        [ "$K" == "82" ]    && xdotool type "-"
        [ "$K" == "84" ]    && xdotool key "ctrl+0"
        [ "$K" == "86" ]    && xdotool type "+"
        [ "$K" == "87" ]    && xdotool key "ctrl+z"
        [ "$K" == "88" ]    && xdotool key "shift+ctrl+z"
        [ "$K" == "90" ]    && xdotool key x
        [ "$K" == "91" ]    && xdotool key d
        [ "$K" == "104" ]   && xdotool key "Return"
        [ "$K" == "106" ]   && xdotool key "w"
        if [ "$K" == "106" ] && [ "$KK" == "106" ]; then
            xdotool key "ctrl+d"
            echo "deseleccionar"
        fi
    fi
    if [ ! "$(echo $P | grep -i inkscape)" == "" ]; then
        [ "$K" == "79" ]  && xdotool key "F1"
        [ "$K" == "80" ]  && xdotool key "shift+F6"
        [ "$K" == "82" ]  && xdotool type "-"
        [ "$K" == "84" ]  && xdotool key "5"
        [ "$K" == "86" ]  && xdotool type "+"
        [ "$K" == "81" ]  && xdotool key "F7"
        [ "$K1" == "87" ]  && xdotool keydown "ctrl"
        [ "$K" == "87" ]  && xdotool keyup "ctrl"
        [ "$K1" == "88" ]  && xdotool keydown "shift"
        [ "$K" == "88" ]  && xdotool keyup "shift"
    fi
    [ ! "$K" == "" ] && KK=$K
done
    sleep 30
done
exit

Teclas
======

1 87
2 88
3 89
4 83
5 84
6 85
7 79
8 80
9 81
0 90
+ 86
- 82
e 104
/ 106
* 63
d 91
